In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

/home/jn/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [3]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'lxml')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'lxml')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css"/>
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 80° F
				</span> <span class="icon weather-icon"> <img alt="mostly_cloudy" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/mostly_cloudy.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search13.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us3.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"/> Lycos
						SWAG</a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2025 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search13.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00f12af56d23cc1e2d16');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 80  f function setdefaultlanguage lang                                      cookie  defaultlanguage   lang    path       expires  3650  domain   lycos com                                    english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge             cdata             function checksubmit           var querybox   document getelementbyid  query           if   querybox value     enter search term            querybox value trim                 querybox value          querybox focus      return false                return true                       lycos       swag mail tripod domains weather angelfire copyright   2025 lycos about careers advertise with us legal privacy help add       lycos search to browser window datalayer   window datalayer          function gtag   datalayer push arguments      gtag  js   new date        gtag  config    g 0wy0kph0zw    window datalayer   window datalayer          function gtag   datalayer push arguments      gtag  js   new date        gtag  config    g 76fjghqnn6         cdata        keyvol   val  00f12af56d23cc1e2d16                 document  ready function e                 owl demo1   owlcarousel           items  6          lazyload   true          navigation   true                    owl demo2   owlcarousel           items  6          lazyload   true          navigation   true                    owl demo3   owlcarousel           items  6          lazyload   true          navigation   true                    owl demo4   owlcarousel           items  6          lazyload   true          navigation   true                          function       use strict        initialize ajax autocomplete       query   autocomplete     serviceurl    https   us search yahoo com sugg gossip gossip us partner output sd1 appid lycos           datatype   jsonp     paramname    command     onsearchcomplete   function originalquery  suggestion       var re   new regexp   b      autocomplete utils escaperegexchars originalquery    gi       return re test suggestion value          onselect   function suggestion           form_query   submit           oninvalidateselection   function            selction ajax   html  you selected  none           transformresult   function _response       var response   typeof _response      string      parsejson _response    _response     return       query   response q      suggestions     map response r  function dataitem         return dataitem k
[13601, 2569, 200, 0]

In [5]:
# print(soupFromUrl('https://www.delinian.com/'))
# print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[13597, 2569, 200, 0]

In [6]:
bangla_url = list(pd.read_csv('../Dataset/URL Data/bangla_spam.csv',delimiter='\t')['URL'])
bangla_url[:10]

['www.dot.gov.bd',
 'https://joinbangladesharmy.army.mil.bd',
 'www.hasinaandfriends.gov.bd',
 'https://joinbangladesharmy.mil.mil.bd',
 'https://joinairforce.baf.mil.bd',
 'www.joinnavy.navy.mil.bd',
 'http://cutt.ly/8CgjCP9',
 'http://joinnavy.navy.mil.bd',
 'www.bida.gov.bd',
 'www.nmst.gov.bd']

In [7]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [8]:
unique_bangla_url = set(bangla_url )

In [9]:
for idx,i in enumerate(unique_bangla_url):
    if '..' in i:
        if 'www' in i:
            unique_bangla_url[idx] = ''
        else:
            unique_bangla_url[idx] = unique_bangla_url[idx].replace('..','.')

In [10]:
unique_bangla_url = [i for i in unique_bangla_url if i!='']

In [11]:
bangla_dataset = {'ham':list(pd.read_csv('../Dataset/URL Data/bangla_spam_ham.csv',delimiter='\t')['URL']),'spam':list(pd.read_csv('../Dataset/URL Data/bangla_spam_spam.csv',delimiter='\t')['URL'])}

In [12]:
bangla_url_in_ham = [0]*len(unique_bangla_url)
bangla_url_in_spam = [0]*len(unique_bangla_url)

for idx,i in enumerate(unique_bangla_url):
    for j in bangla_dataset['ham']:
        if not isinstance(j, str):
            continue
        if i in j:
            bangla_url_in_ham[idx] = 1
            break
    for j in bangla_dataset['spam']:
        if not isinstance(j, str):
            continue
        if i in j:
            bangla_url_in_spam[idx] = 1
            break

print(bangla_url_in_ham.count(1))
print(bangla_url_in_spam.count(1))

43
48

In [13]:
common_urls = []
for i in range(len(bangla_url_in_ham)):
    if bangla_url_in_ham[i]==bangla_url_in_spam[i]:
        common_urls.append(unique_bangla_url[i])

len(common_urls)

3

In [14]:
bangla_dataset['Unique Url'] = unique_bangla_url

In [15]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [16]:
bangla_dataset['FQDN'] = [FQDN(i) for i in bangla_dataset['Unique Url']]

len(set(bangla_dataset['FQDN']))

58

In [17]:
a = soupFromUrl('https://facebook.com')

print(a)

[78008, 32747, 200, 0]

The below query last ran on 5 October 2025

In [18]:
website_size, text_content_length, status_code, parked = [],[],[],[]

for i in bangla_dataset['FQDN']:
    a = soupFromUrl('https://'+i)

    website_size.append(a[0])
    text_content_length.append(a[1])
    status_code.append(a[2])
    parked.append(a[3])


# parked = [0]*len(bangla_dataset)

# for idx,i in enumerate(bangla_dataset['FQDN']):
#     if bangla_dataset['Status Code'][idx]==200:
#         a = soupFromUrl('https://'+i)
#         parked[idx] = a[3]
#         # break

# print(parked)

In [19]:
bangla_dataset['Website Size in KB'] = website_size
bangla_dataset['Website Textual Content Length'] = text_content_length
bangla_dataset['Status Code'] = status_code

bangla_dataset['Parked'] = parked

In [20]:
for i in bangla_dataset:
    print(len(bangla_dataset[i]))

90
89
88
88
88
88
88
88

In [21]:
bangla_dataset['ham'] = bangla_url_in_ham
bangla_dataset['spam'] = bangla_url_in_spam

In [22]:
bangla_dataset

{'ham': [0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1],
 'spam': [1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0],
 'Unique Url': ['https://bKa.sh/8app',
  'https://rrj.nu/VucpYxnb',
  'https://click.daraz.com.bd/e/_C69OCr',
  'https://rrj.nu/kFGj26Cd',
  'https://ebl.com.bd/Eid-Offers-2023#travel',
  'www.nmst.gov.bd',
  'https://bka.sh/dec1tkoffr',
  'https://cutt.ly/Vwqu8c6C',
  'http://joinnavy.navy.mil.bd',
  'https://joinbangladesharmy.army.mil.bd',
  'www.annisagallerybd.com',
  'http://bit.ly/3IVA0tu',
  'http://bdlaws.minlaw.gov.bd',
  'www.banglaacademy.gov.bd',
  'www.joinnavy.navy.mil.bd',
  'https://tinyurl.com/wsis21',
  'https://mygp.li/r2',
  'https://tinyurl.com/bblabd',
  'https://click.daraz.com.bd/e/_CY8qr9',
  'https://joinairforce.baf.mil.bd',
  'https://onelink.to/bgqm6h',
  'https://mygp.li/a0',
  'https://gic.im/ec',
  'www.youthpowerhouse.org/shyva',
  'https://gic.im/noor/',
  'www.berc.org.bd',
  'www.themallbd.com',
  'https://www.chorki.com/redeem',
  'https://bit.ly/3Inwyh6',
  'www.telecomdept.gov.bd',
  'www.joinnavy.mil.bd',
  'https://robi.epicon.in',
  'www.stripe.clothing',
  'http://www.amiprobashi.com/a',
  'https://click.daraz.com.bd/e/_CUvX0N',
  'https://joinbangladesharmy.mil.mil.bd',
  'www.bida.gov.bd',
  'https://bka.sh/bkblnet',
  'www.bscl.gov.bd',
  'https://bit.ly/3pZsYkP',
  'https://seafoodexpobd.com',
  'http://cutt.ly/8CgjCP9',
  'www.moca.gov.bd',
  'https:joinbangladesharmy.army.mil.bd',
  'www.police.gov.bd',
  'https://tinyurl.com/BBLFDO',
  'https://tinyurl.com/BBLDCRP01',
  'https://bka.sh/bmy',
  'www.diabetes-covid19.org',
  'https://cutt.ly/MMMjbSM',
  'www.pkb.gov.bd',
  'https://bit.ly/2YBHO5U',
  'www.sheikhrussel.gov.bd',
  'https://gp.mygp.li/lt',
  'www.surokkha.gov.bd',
  'https://quiz.priyo.com',
  'www.hasinaandfriends.gov.bd',
  'https://quiz.digitalbangladesh.gov.bd',
  'https://bit.ly/3XULpXy',
  'http://chaldal.com/fresh-fruit',
  'http://ujjwala.co',
  'www.moysports.gov.bd',
  'www.nsda.gov.bd',
  'http://ow.ly/2BAY50N8JCL',
  'http://joinairforce.baf.mil.bd',
  'https://click.daraz.com.bd/e/_CZIXHP',
  'https://cutt.ly/MyDrive',
  'https://cutt.ly/iEW25U8',
  'www.digitalbangladesh.gov.bd',
  'https://bit.ly/2W2mTHH',
  'https://cutt.ly/0UjDTpk',
  'https://cutt.ly/i8ZZmNI',
  'www.dot.gov.bd',
  'www.bncu.gov.bd',
  'https://ebl.com.bd/Eid-Offers-2023#cattle',
  'www.bb.org.bd/en/index.php/currency/securityfeature',
  'https://cut.ly/1OyInS',
  'https://tinyurl.com/bblgth',
  'http://t.ly/srcQ',
  'www.dos.gov.bd',
  'www.joinbangladeshairforce.mil.bd',
  'http://mysports.com.bd',
  'https://click.daraz.com.bd/e/_CY9njh',
  'https://cutt.ly/Awttr5dc',
  'https://t.ly/vnnB',
  'https://cutt.ly/J1xS6vD',
  'https://tinyurl.com/SixseasonsBrac',
  'https://www.facebook.com/cybercrimedb'],
 'FQDN': ['bKa.sh',
  'rrj.nu',
  'click.daraz.com.bd',
  'rrj.nu',
  'ebl.com.bd',
  'www.nmst.gov.bd',
  'bka.sh',
  'cutt.ly',
  'joinnavy.navy.mil.bd',
  'joinbangladesharmy.army.mil.bd',
  'www.annisagallerybd.com',
  'bit.ly',
  'bdlaws.minlaw.gov.bd',
  'www.banglaacademy.gov.bd',
  'www.joinnavy.navy.mil.bd',
  'tinyurl.com',
  'mygp.li',
  'tinyurl.com',
  'click.daraz.com.bd',
  'joinairforce.baf.mil.bd',
  'onelink.to',
  'mygp.li',
  'gic.im',
  'www.youthpowerhouse.org',
  'gic.im',
  'www.berc.org.bd',
  'www.themallbd.com',
  'www.chorki.com',
  'bit.ly',
  'www.telecomdept.gov.bd',
  'www.joinnavy.mil.bd',
  'robi.epicon.in',
  'www.stripe.clothing',
  'www.amiprobashi.com',
  'click.daraz.com.bd',
  'joinbangladesharmy.mil.mil.bd',
  'www.bida.gov.bd',
  'bka.sh',
  'www.bscl.gov.bd',
  'bit.ly',
  'seafoodexpobd.com',
  'cutt.ly',
  'www.moca.gov.bd',
  'https.',
  'www.police.gov.bd',
  'tinyurl.com',
  'tinyurl.com',
  'bka.sh',
  'www.diabetes-covid19.org',
  'cutt.ly',
  'www.pkb.gov.bd',
  'bit.ly',
  'www.sheikhrussel.gov.bd',
  'gp.mygp.li',
  'www.surokkha.gov.bd',
  'quiz.priyo.com',
  'www.hasinaandfriends.gov.bd',
  'quiz.digitalbangladesh.gov.bd',
  'bit.ly',
  'chaldal.com',
  'ujjwala.co',
  'www.moysports.gov.bd',
  'www.nsda.gov.bd',
  'ow.ly',
  'joinairforce.baf.mil.bd',
  'click.daraz.com.bd',
  'cutt.ly',
  'cutt.ly',
  'www.digitalbangladesh.gov.bd',
  'bit.ly',
  'cutt.ly',
  'cutt.ly',
  'www.dot.gov.bd',
  'www.bncu.gov.bd',
  'ebl.com.bd',
  'www.bb.org.bd',
  'cut.ly',
  'tinyurl.com',
  't.ly',
  'www.dos.gov.bd',
  'www.joinbangladeshairforce.mil.bd',
  'mysports.com.bd',
  'click.daraz.com.bd',
  'cutt.ly',
  't.ly',
  'cutt.ly',
  'tinyurl.com',
  'www.facebook.com'],
 'Website Size in KB': [1833,
  0,
  559826,
  0,
  63664,
  0,
  1833,
  114920,
  25172,
  75390,
  0,
  137740,
  0,
  0,
  25172,
  13611,
  0,
  13611,
  561669,
  0,
  301512,
  436341,
  26854,
  38187,
  26854,
  0,
  0,
  1114680,
  137740,
  0,
  0,
  0,
  0,
  27486,
  559781,
  0,
  130764,
  1833,
  145520,
  137740,
  114288,
  114920,
  0,
  0,
  0,
  13611,
  13611,
  1833,
  0,
  114920,
  0,
  137740,
  0,
  0,
  0,
  0,
  0,
  0,
  137740,
  1946750,
  0,
  0,
  0,
  299040,
  0,
  560678,
  114920,
  114920,
  0,
  137740,
  114920,
  114920,
  0,
  0,
  63664,
  87808,
  114920,
  13611,
  80585,
  0,
  0,
  70131,
  559219,
  114920,
  80585,
  114920,
  13611,
  78011],
 'Website Textual Content Length': [0,
  0,
  171763,
  0,
  6987,
  0,
  0,
  27254,
  6708,
  13162,
  0,
  28069,
  0,
  0,
  6708,
  0,
  0,
  0,
  172406,
  0,
  2369,
  291495,
  5475,
  1857,
  5475,
  0,
  0,
  1082533,
  28069,
  0,
  0,
  0,
  0,
  63,
  171800,
  0,
  19827,
  0,
  10523,
  28069,
  59767,
  27254,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  27254,
  0,
  28069,
  0,
  0,
  0,
  0,
  0,
  0,
  28069,
  1227928,
  0,
  0,
  0,
  155115,
  0,
  172019,
  27254,
  27254,
  0,
  28069,
  27254,
  27254,
  0,
  0,
  6987,
  6340,
  27254,
  0,
  4973,
  0,
  0,
  8901,
  171394,
  27254,
  4973,
  27254,
  0,
  32748],
 'Status Code': [200,
  404,
  200,
  404,
  200,
  -1,
  200,
  200,
  200,
  200,
  -1,
  200,
  -1,
  -1,
  200,
  200,
  -1,
  200,
  200,
  -1,
  200,
  200,
  200,
  200,
  200,
  -1,
  403,
  200,
  200,
  -1,
  -1,
  500,
  -1,
  200,
  200,
  -1,
  200,
  200,
  200,
  200,
  200,
  200,
  -1,
  -1,
  -1,
  200,
  200,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  -1,
  -1,
  530,
  -1,
  -1,
  200,
  200,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  200,
  200,
  -1,
  200,
  200,
  200,
  -1,
  -1,
  200,
  200,
  200,
  200,
  200,
  -1,
  -1,
  200,
  200,
  200,
  200,
  200,
  200,
  200],
 'Parked': [1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0]}

In [23]:
# bangla_dataset = pd.read_csv('../Dataset/URL Data/bangla Websites Analysis.csv')
bangla_dataset = pd.DataFrame.from_dict(bangla_dataset)
bangla_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,https://bKa.sh/8app,bKa.sh,1833,0,200,1
1,0,1,https://rrj.nu/VucpYxnb,rrj.nu,0,0,404,0
2,0,1,https://click.daraz.com.bd/e/_C69OCr,click.daraz.com.bd,559826,171763,200,1
3,0,1,https://rrj.nu/kFGj26Cd,rrj.nu,0,0,404,0
4,0,1,https://ebl.com.bd/Eid-Offers-2023#travel,ebl.com.bd,63664,6987,200,0

In [24]:
bangla_dataset['Status Code'].value_counts()

Status Code
 200    53
-1      30
 404     2
 403     1
 500     1
 530     1
Name: count, dtype: int64

In [26]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
bangla_dataset.loc[bangla_dataset['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [27]:
bangla_dataset['Status Code'].value_counts()

Status Code
 200    54
-1      30
 404     2
 500     1
 530     1
Name: count, dtype: int64

In [28]:
print(len(bangla_dataset[(bangla_dataset['Status Code']==200) & (bangla_dataset['ham']==1)]))
print(len(bangla_dataset[(bangla_dataset['Status Code']==200) & (bangla_dataset['spam']==1)]))

17
38

In [29]:
bangla_dataset['Parked'].value_counts()

Parked
0    65
1    23
Name: count, dtype: int64

In [30]:
print(len(bangla_dataset[(bangla_dataset['Parked']==1) & (bangla_dataset['ham']==1)]))
print(len(bangla_dataset[(bangla_dataset['Parked']==1) & (bangla_dataset['ham']==0)]))

3
20

In [32]:
bangla_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,https://bKa.sh/8app,bKa.sh,1833,0,200,1
1,0,1,https://rrj.nu/VucpYxnb,rrj.nu,0,0,404,0
2,0,1,https://click.daraz.com.bd/e/_C69OCr,click.daraz.com.bd,559826,171763,200,1
3,0,1,https://rrj.nu/kFGj26Cd,rrj.nu,0,0,404,0
4,0,1,https://ebl.com.bd/Eid-Offers-2023#travel,ebl.com.bd,63664,6987,200,0

In [33]:
bangla_dataset.to_csv('../Dataset/URL Data/bangla Websites Analysis.csv', index=None)

In [34]:
len(bangla_dataset)

88