In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [3]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'lxml')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'lxml')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css"/>
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 65° F
				</span> <span class="icon weather-icon"> <img alt="night_mostly_clear" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/night_mostly_clear.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us3.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"/> Lycos
						SWAG</a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2024 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00cd641073104d642f57');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 65  f english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge lycos       swag mail tripod domains weather angelfire copyright   2024 lycos about careers advertise with us legal privacy help add       lycos search to browser
[13607, 328, 200, 0]

In [5]:
# print(soupFromUrl('https://www.delinian.com/'))
# print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[13607, 328, 200, 0]

In [6]:
Korean_url = list(pd.read_csv('../Dataset/URL Data/Korean Dataset.csv',delimiter='\t')['URL'])
Korean_url[:10]

['www.coinonve.com',
 'https://play.google.com/store/apps/details?id=com.teamviewer.quicksuport.market엄마이링크클릭해서설치하고열기하면귀하의아이디라고9자리로',
 'https://play.google.com',
 'https://ya.mba/3PZ',
 'https://url.kr/fn8ocq',
 'https://play.google.com/store/ap',
 'www.coinoena.com',
 'www.coincneo.com',
 'https://ko.gl/ac60',
 'https://utka.su/jpmh8']

In [7]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [8]:
unique_Korean_url = set(Korean_url )

In [9]:
for idx,i in enumerate(unique_Korean_url):
    if '..' in i:
        if 'www' in i:
            unique_Korean_url[idx] = ''
        else:
            unique_Korean_url[idx] = unique_Korean_url[idx].replace('..','.')

In [10]:
unique_Korean_url = [i for i in unique_Korean_url if i!='']

In [11]:
Korean_dataset = {'ham':list(pd.read_csv('../Dataset/URL Data/Korean Dataset Ham.csv',delimiter='\t')['URL']),'spam':list(pd.read_csv('../Dataset/URL Data/Korean Dataset Spam.csv',delimiter='\t')['URL'])}

In [12]:
Korean_url_in_ham = [0]*len(unique_Korean_url)
Korean_url_in_spam = [0]*len(unique_Korean_url)

for idx,i in enumerate(unique_Korean_url):
    for j in Korean_dataset['ham']:
        if not isinstance(j, str):
            continue
        if i in j:
            Korean_url_in_ham[idx] = 1
            break
    for j in Korean_dataset['spam']:
        if not isinstance(j, str):
            continue
        if i in j:
            Korean_url_in_spam[idx] = 1
            break

print(Korean_url_in_ham.count(1))
print(Korean_url_in_spam.count(1))

3
116

In [13]:
common_urls = []
for i in range(len(Korean_url_in_ham)):
    if Korean_url_in_ham[i]==Korean_url_in_spam[i]:
        common_urls.append(unique_Korean_url[i])

len(common_urls)

1

In [14]:
Korean_dataset['Unique Url'] = unique_Korean_url

In [15]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [16]:
Korean_dataset['FQDN'] = [FQDN(i) for i in Korean_dataset['Unique Url']]

len(set(Korean_dataset['FQDN']))

unable to cache publicsuffix.org-tlds.{'urls': ('https://publicsuffix.org/list/public_suffix_list.dat', 'https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat'), 'fallback_to_snapshot': True} in c:\ProgramData\anaconda3\Lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json. This could refresh the Public Suffix List over HTTP every app startup. Construct your `TLDExtract` with a writable `cache_dir` or set `cache_dir=False` to silence this warning. [WinError 5] Access is denied: 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\tldextract\\.suffix_cache'

75

In [17]:
a = soupFromUrl('https://facebook.com')

print(a)

[74355, 645, 200, 0]

The below query last ran on 7 Novemebr 2024

In [18]:
website_size, text_content_length, status_code, parked = [],[],[],[]

for i in Korean_dataset['FQDN']:
    a = soupFromUrl('https://'+i)

    website_size.append(a[0])
    text_content_length.append(a[1])
    status_code.append(a[2])
    parked.append(a[3])


# parked = [0]*len(Korean_dataset)

# for idx,i in enumerate(Korean_dataset['FQDN']):
#     if Korean_dataset['Status Code'][idx]==200:
#         a = soupFromUrl('https://'+i)
#         parked[idx] = a[3]
#         # break

# print(parked)

In [19]:
Korean_dataset['Website Size in KB'] = website_size
Korean_dataset['Website Textual Content Length'] = text_content_length
Korean_dataset['Status Code'] = status_code

Korean_dataset['Parked'] = parked

In [20]:
for i in Korean_dataset:
    print(len(Korean_dataset[i]))

3
127
120
120
120
120
120
120

In [21]:
Korean_dataset['ham'] = Korean_url_in_ham
Korean_dataset['spam'] = Korean_url_in_spam

In [22]:
Korean_dataset

{'ham': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0],
 'spam': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1],
 'Unique Url': ['www.coincneo.com',
  'http://tinyurl.com/yfuwrq28',
  'http://tinyurl.com/y7yxy5gm',
  'http://fff.kr/auEM',
  'https://soo.gd/u053?sco',
  'www.coinsnoe.com',
  'https://tinyurl.com/y54uxysk',
  'https://dokdo.in/LYD',
  'https://open.kakao.com/o/scINi1Bc',
  'https://vo.la/FfaFZ',
  'https://bit.ly/2lw2FG7',
  'www.coinoene.com',
  'https://ya.mba/3Pr',
  'www.coinoine.com',
  'https://news.kbs.co.kr/vod/program.do?bcd=0076&ref=pMenu#20211222&1',
  'www.coinoenl.com',
  'www.coinoena.com',
  'www.coineonc.com',
  'https://bit/ly/2ktOYHz?gyhfko제폰번호가해킹당해서택배문자가여러명에게가고있습니다.오해없으시기바랍니다.',
  'http://www.iPhone-korea.com',
  'http://na.to/a2f9',
  'https://utka.su/jpmh8',
  'https://s.id/tUxzA',
  'http://me2.kr/1xg9',
  'http://click.gl/FVUX99',
  'www.coinonme.com',
  'https://open.kakao.com/o/sbNK3Cvc',
  'https://kr.pe/RSM',
  'https://han.gl/b9GQL',
  'www.coinonve.com',
  'www.mxc.kr/',
  'https://news.kbs.co.kr/vod/program.do?bcd=0076&ref=pMenu#20211227&1',
  'https://ya.mba/3Pq',
  'www.modetorr.com',
  'http://www.iPhone-',
  'www.mrte.ch/1i2i',
  'http://me2.do/5U0pZ4dD',
  'https://bit.ly/',
  'http://tinyurl.com/.yxqxhu8b',
  'www.coinoens.com',
  'http://search.t-foemss.iego.net:88/',
  'www.prerin.com/jyun9095',
  'https://ko.gl/MpDP',
  'www.coinsone.net',
  'https://bit.ly/2GCc3D0',
  'www.coinonex.net',
  'http://asq.kr/BTcKCwV7hMDpK',
  'https://url.vet/rlm6z',
  'www.kp-ap.com',
  'www.coinocone.com',
  'www.minwono.com/',
  'https://play.google.com/store/apps/details?id=com.teamviewer.quicksupport.market&hl=ko',
  'www.coinuone.com',
  'https://han.gl/injKS',
  'www.coinnoven.com',
  'https://s.id/tsSsH',
  'https://start.teamviewer.com을방문해TeamViewerID1074460051을(를)입력할수있습니다.10자리야',
  'https://play.google.com/store/apps/details?id=com.teamviewer.quicksupport.market',
  'http://twr.kr/INTE',
  'https://cutt.ly/',
  'http://gg.gg/nc4cj',
  'https://han.gl/검진기간안내',
  'www.cjmong.pro',
  'https://play.google.com/store/apps/',
  'https://bit.ly/2KaXGE0',
  'https://chl.li/8gP87',
  'http://urnic.com/fqY',
  'http://tinyurl.com/.u.jk6ruxe',
  'https://forms.gle/AL5niUDQtYZ2EtzK9',
  'www.coinvone.live',
  'http://ooy.kr/LHb',
  'http://1url.kr/vsd5',
  'http://tinyurl.com/',
  'http://23.245.213.249/',
  'https://tinyurl.com/y8xcgc4xee',
  'https://ya.mba/3PZ',
  'https://play.google.com/store/ap',
  'https://play.google.com',
  'https://url.kr/fn8ocq',
  'https://soo.gd/8ja0',
  'https://play.google.com/store/',
  'www.ynmglobal6.com',
  'http://1url.kr/',
  'http://www.sktanycare.com/',
  'http://tuney.kr/',
  'www.coinoen.com',
  'https://vo.la/NigLw',
  'https://bit.ly/2Vhf6Y4',
  'http://me2.do/',
  'http://shorturl.at/rGLV7',
  'https://play.google.com/store/apps/details?id=com.teamviewer.quicksuport.market엄마이링크클릭해서설치하고열기하면귀하의아이디라고9자리로',
  'http://11st.kr/!',
  'www.coinonie.com',
  'https://ko.gl/ac60',
  'https://dokdo.in/0r0',
  'https://bit.ly/2qMASml?tukmjw',
  'http://grep.kr/QxC',
  'https://is.gd/',
  'http://me2.do/xmf3GQWJ',
  'https://bit.ly/2D6GFql?llu',
  'www.bithumb.com',
  'https://han.gl/MJ7NK',
  'www.coinnaoe.com',
  'http://na.to/azwR',
  'https://ko.gl/NIYv',
  'https://start.teamviewer.com/1074460051을열어기기에10연결하십시오.또는https://start.teamviewer.com을방문해TeamViewerID1074460051을(를)입력할수',
  'https://dokdo.in/tYM',
  'http://3asd1f1h.monster/?',
  'https://is.gd/mms_korea',
  'https://ko.gl/',
  'http://bit.do/navern',
  'https://ols.sbiz.or.kr/',
  'https://utka.su/7EOjs',
  'https://bit.ly',
  'https://kr.pe/SZY',
  'http://fimg3.pann.com/new/download.jsp?FileID=35774362',
  'http://tinyurl.com/y7fec8o4',
  'https://dokdo.in/coupang',
  'https://tinyurl.com/yk4mvdr7',
  'https://tinyurl.com/'],
 'FQDN': ['www.coincneo.com',
  'tinyurl.com',
  'tinyurl.com',
  'fff.kr',
  'soo.gd',
  'www.coinsnoe.com',
  'tinyurl.com',
  'dokdo.in',
  'open.kakao.com',
  'vo.la',
  'bit.ly',
  'www.coinoene.com',
  'ya.mba',
  'www.coinoine.com',
  'news.kbs.co.kr',
  'www.coinoenl.com',
  'www.coinoena.com',
  'www.coineonc.com',
  'bit.',
  'www.iPhone-korea.com',
  'na.to',
  'utka.su',
  's.id',
  'me2.kr',
  'click.gl',
  'www.coinonme.com',
  'open.kakao.com',
  'kr.pe',
  'han.gl',
  'www.coinonve.com',
  'www.mxc.kr',
  'news.kbs.co.kr',
  'ya.mba',
  'www.modetorr.com',
  'www.iPhone-.',
  'www.mrte.ch',
  'me2.do',
  'bit.ly',
  'tinyurl.com',
  'www.coinoens.com',
  'search.t-foemss.iego.net',
  'www.prerin.com',
  'ko.gl',
  'www.coinsone.net',
  'bit.ly',
  'www.coinonex.net',
  'asq.kr',
  'url.vet',
  'www.kp-ap.com',
  'www.coinocone.com',
  'www.minwono.com',
  'play.google.com',
  'www.coinuone.com',
  'han.gl',
  'www.coinnoven.com',
  's.id',
  'start.teamviewer.com을방문해TeamViewerID1074460051을(를)입력할수있습니다.10자리야.',
  'play.google.com',
  'twr.kr',
  'cutt.ly',
  'gg.gg',
  'han.gl',
  'www.cjmong.pro',
  'play.google.com',
  'bit.ly',
  'chl.li',
  'urnic.com',
  'tinyurl.com',
  'forms.gle',
  'www.coinvone.live',
  'ooy.kr',
  '1url.kr',
  'tinyurl.com',
  '23.245.213.249.',
  'tinyurl.com',
  'ya.mba',
  'play.google.com',
  'play.google.com',
  'url.kr',
  'soo.gd',
  'play.google.com',
  'www.ynmglobal6.com',
  '1url.kr',
  'www.sktanycare.com',
  'tuney.kr',
  'www.coinoen.com',
  'vo.la',
  'bit.ly',
  'me2.do',
  'shorturl.at',
  'play.google.com',
  '11st.kr',
  'www.coinonie.com',
  'ko.gl',
  'dokdo.in',
  'bit.ly',
  'grep.kr',
  'is.gd',
  'me2.do',
  'bit.ly',
  'www.bithumb.com',
  'han.gl',
  'www.coinnaoe.com',
  'na.to',
  'ko.gl',
  'start.teamviewer.com',
  'dokdo.in',
  '3asd1f1h.monster',
  'is.gd',
  'ko.gl',
  'bit.do',
  'ols.sbiz.or.kr',
  'utka.su',
  'bit.ly',
  'kr.pe',
  'fimg3.pann.com',
  'tinyurl.com',
  'dokdo.in',
  'tinyurl.com',
  'tinyurl.com'],
 'Website Size in KB': [0,
  13574,
  13574,
  0,
  0,
  0,
  13574,
  0,
  22724,
  40215,
  105701,
  0,
  1739,
  0,
  783,
  0,
  0,
  0,
  0,
  0,
  15481,
  0,
  111217,
  42333,
  0,
  0,
  22724,
  50292,
  50291,
  0,
  2754,
  783,
  1739,
  0,
  0,
  0,
  0,
  105701,
  13574,
  0,
  0,
  0,
  44371,
  0,
  105701,
  0,
  42333,
  42333,
  0,
  0,
  0,
  1758787,
  0,
  50292,
  0,
  111217,
  0,
  1758012,
  0,
  104077,
  0,
  50291,
  0,
  1757970,
  105701,
  17784,
  83695,
  13574,
  0,
  0,
  0,
  0,
  13574,
  0,
  13574,
  1739,
  1757971,
  1757977,
  25437,
  0,
  1757970,
  0,
  0,
  80,
  5300,
  0,
  40215,
  105701,
  0,
  17371,
  1758015,
  11333,
  0,
  44371,
  0,
  105701,
  75117,
  0,
  0,
  105701,
  8910,
  50292,
  0,
  15621,
  44371,
  14258,
  0,
  0,
  0,
  44371,
  0,
  0,
  0,
  105701,
  50291,
  0,
  13574,
  0,
  13574,
  13574],
 'Website Textual Content Length': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  946,
  1561,
  8533,
  0,
  123,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  396,
  0,
  4346,
  2198,
  0,
  0,
  946,
  2843,
  2842,
  0,
  110,
  0,
  123,
  0,
  0,
  0,
  0,
  8533,
  0,
  0,
  0,
  0,
  2166,
  0,
  8533,
  0,
  2198,
  2198,
  0,
  0,
  0,
  3285,
  0,
  2843,
  0,
  4346,
  0,
  3301,
  0,
  15546,
  0,
  2842,
  0,
  3285,
  8533,
  518,
  4657,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  123,
  3285,
  3285,
  1174,
  0,
  3285,
  0,
  0,
  0,
  155,
  0,
  1561,
  8533,
  0,
  1584,
  3301,
  0,
  0,
  2166,
  0,
  8533,
  1007,
  0,
  0,
  8533,
  0,
  2843,
  0,
  416,
  2166,
  727,
  0,
  0,
  0,
  2166,
  0,
  0,
  0,
  8533,
  2842,
  0,
  0,
  0,
  0,
  0],
 'Status Code': [-1,
  200,
  200,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  200,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  -1,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  200,
  -1,
  -1,
  200,
  200,
  200,
  -1,
  200,
  200,
  200,
  -1,
  -1,
  200,
  404,
  200,
  200,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  200,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  -1,
  200,
  200,
  200,
  200,
  200,
  400,
  -1,
  -1,
  -1,
  200,
  -1,
  200,
  200,
  200,
  200,
  200,
  -1,
  200,
  -1,
  -1,
  200,
  200,
  -1,
  200,
  200,
  404,
  200,
  200,
  200,
  -1,
  200,
  -1,
  200,
  200,
  403,
  404,
  200,
  200,
  200,
  -1,
  200,
  200,
  200,
  -1,
  -1,
  403,
  200,
  -1,
  -1,
  -1,
  200,
  200,
  403,
  200,
  -1,
  200,
  200],
 'Parked': [0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1]}

In [23]:
# Korean_dataset = pd.read_csv('../Dataset/URL Data/Korean Websites Analysis.csv')
Korean_dataset = pd.DataFrame.from_dict(Korean_dataset)
Korean_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,www.coincneo.com,www.coincneo.com,0,0,-1,0
1,0,1,http://tinyurl.com/yfuwrq28,tinyurl.com,13574,0,200,1
2,0,1,http://tinyurl.com/y7yxy5gm,tinyurl.com,13574,0,200,1
3,0,1,http://fff.kr/auEM,fff.kr,0,0,-1,0
4,0,1,https://soo.gd/u053?sco,soo.gd,0,0,-1,0

In [24]:
Korean_dataset['Status Code'].value_counts()

Status Code
 200    64
-1      49
 404     3
 403     3
 400     1
Name: count, dtype: int64

In [25]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
Korean_dataset.loc[Korean_dataset['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [26]:
Korean_dataset['Status Code'].value_counts()

Status Code
 200    67
-1      49
 404     3
 400     1
Name: count, dtype: int64

In [33]:
print(len(Korean_dataset[(Korean_dataset['Status Code']==200) & (Korean_dataset['ham']==1)]))
print(len(Korean_dataset[(Korean_dataset['Status Code']==200) & (Korean_dataset['ham']==0)]))

3
64

In [28]:
Korean_dataset['Parked'].value_counts()

Parked
0    96
1    24
Name: count, dtype: int64

In [29]:
print(len(Korean_dataset[(Korean_dataset['Parked']==1) & (Korean_dataset['ham']==1)]))
print(len(Korean_dataset[(Korean_dataset['Parked']==1) & (Korean_dataset['ham']==0)]))

2
22

In [30]:
Korean_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,www.coincneo.com,www.coincneo.com,0,0,-1,0
1,0,1,http://tinyurl.com/yfuwrq28,tinyurl.com,13574,0,200,1
2,0,1,http://tinyurl.com/y7yxy5gm,tinyurl.com,13574,0,200,1
3,0,1,http://fff.kr/auEM,fff.kr,0,0,-1,0
4,0,1,https://soo.gd/u053?sco,soo.gd,0,0,-1,0

In [31]:
Korean_dataset.to_csv('../Dataset/URL Data/Korean Websites Analysis.csv', index=None)