In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [3]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'lxml')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'lxml')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css"/>
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 71° F
				</span> <span class="icon weather-icon"> <img alt="cloudy" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/cloudy.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us3.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"/> Lycos
						SWAG</a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2025 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00ca2c854c18cdfdd853');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 71  f english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge lycos       swag mail tripod domains weather angelfire copyright   2025 lycos about careers advertise with us legal privacy help add       lycos search to browser
[13583, 328, 200, 0]

In [5]:
# print(soupFromUrl('https://www.delinian.com/'))
# print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[13587, 328, 200, 0]

In [8]:
swahili_data_url = list(pd.read_csv('../URL Data/swahili_data.csv',delimiter='\t')['URL'])
swahili_data_url[:10]

['https://onelink.to/xanf67',
 'https://bit.ly/3Nhs27X',
 'http://onelink.to/xanf67',
 'https://onelink.to/xanf67',
 'https://onelink.to/xanf67',
 'https://onelink.to/xanf67',
 'https://bit.ly/M-PesaTC',
 'https://onelink.to/xanf67',
 'https://onelink.to/xanf67',
 'https://onelink.to/xanf67']

In [9]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [10]:
unique_swahili_data_url = set(swahili_data_url )

In [11]:
for idx,i in enumerate(unique_swahili_data_url):
    if '..' in i:
        if 'www' in i:
            unique_swahili_data_url[idx] = ''
        else:
            unique_swahili_data_url[idx] = unique_swahili_data_url[idx].replace('..','.')

In [12]:
unique_swahili_data_url = [i for i in unique_swahili_data_url if i!='']

In [14]:
swahili_data_dataset = {'ham':list(pd.read_csv('../URL Data/swahili_data_ham.csv',delimiter='\t')['URL']),'spam':list(pd.read_csv('../URL Data/swahili_data_spam.csv',delimiter='\t')['URL'])}

In [15]:
swahili_data_url_in_ham = [0]*len(unique_swahili_data_url)
swahili_data_url_in_spam = [0]*len(unique_swahili_data_url)

for idx,i in enumerate(unique_swahili_data_url):
    for j in swahili_data_dataset['ham']:
        if not isinstance(j, str):
            continue
        if i in j:
            swahili_data_url_in_ham[idx] = 1
            break
    for j in swahili_data_dataset['spam']:
        if not isinstance(j, str):
            continue
        if i in j:
            swahili_data_url_in_spam[idx] = 1
            break

print(swahili_data_url_in_ham.count(1))
print(swahili_data_url_in_spam.count(1))

9
0

In [16]:
common_urls = []
for i in range(len(swahili_data_url_in_ham)):
    if swahili_data_url_in_ham[i]==swahili_data_url_in_spam[i]:
        common_urls.append(unique_swahili_data_url[i])

len(common_urls)

0

In [17]:
swahili_data_dataset['Unique Url'] = unique_swahili_data_url

In [18]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [19]:
swahili_data_dataset['FQDN'] = [FQDN(i) for i in swahili_data_dataset['Unique Url']]

len(set(swahili_data_dataset['FQDN']))

5

In [20]:
a = soupFromUrl('https://facebook.com')

print(a)

[77867, 613, 200, 0]

The below query last ran on 5 October 2025

In [21]:
website_size, text_content_length, status_code, parked = [],[],[],[]

for i in swahili_data_dataset['FQDN']:
    a = soupFromUrl('https://'+i)

    website_size.append(a[0])
    text_content_length.append(a[1])
    status_code.append(a[2])
    parked.append(a[3])


# parked = [0]*len(swahili_data_dataset)

# for idx,i in enumerate(swahili_data_dataset['FQDN']):
#     if swahili_data_dataset['Status Code'][idx]==200:
#         a = soupFromUrl('https://'+i)
#         parked[idx] = a[3]
#         # break

# print(parked)

In [22]:
swahili_data_dataset['Website Size in KB'] = website_size
swahili_data_dataset['Website Textual Content Length'] = text_content_length
swahili_data_dataset['Status Code'] = status_code

swahili_data_dataset['Parked'] = parked

In [23]:
for i in swahili_data_dataset:
    print(len(swahili_data_dataset[i]))

31
0
9
9
9
9
9
9

In [24]:
swahili_data_dataset['ham'] = swahili_data_url_in_ham
swahili_data_dataset['spam'] = swahili_data_url_in_spam

In [25]:
swahili_data_dataset

{'ham': [1, 1, 1, 1, 1, 1, 1, 1, 1],
 'spam': [0, 0, 0, 0, 0, 0, 0, 0, 0],
 'Unique Url': ['www.zap.co.mz',
  'http://onelink.to/xanf67',
  'https://onelink.to/xanf67',
  'http://movtv.co.mz',
  'https://bit.ly/M-PesaTC',
  'https://bit.ly/2Wbzubn',
  'https://bit.ly/3Nhs27X',
  'https://bit.ly/3Lt7QAy',
  'https://yabadoo.tv/client/tmcel'],
 'FQDN': ['www.zap.co.mz',
  'onelink.to',
  'onelink.to',
  'movtv.co.mz',
  'bit.ly',
  'bit.ly',
  'bit.ly',
  'bit.ly',
  'yabadoo.tv'],
 'Website Size in KB': [7707,
  301512,
  301512,
  0,
  137740,
  137740,
  137740,
  137740,
  31743],
 'Website Textual Content Length': [10,
  2288,
  2288,
  0,
  10189,
  10189,
  10189,
  10189,
  1696],
 'Status Code': [200, 200, 200, -1, 200, 200, 200, 200, 200],
 'Parked': [0, 0, 0, 0, 1, 1, 1, 1, 0]}

In [26]:
# swahili_data_dataset = pd.read_csv('../Dataset/URL Data/swahili_data Websites Analysis.csv')
swahili_data_dataset = pd.DataFrame.from_dict(swahili_data_dataset)
swahili_data_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,1,0,www.zap.co.mz,www.zap.co.mz,7707,10,200,0
1,1,0,http://onelink.to/xanf67,onelink.to,301512,2288,200,0
2,1,0,https://onelink.to/xanf67,onelink.to,301512,2288,200,0
3,1,0,http://movtv.co.mz,movtv.co.mz,0,0,-1,0
4,1,0,https://bit.ly/M-PesaTC,bit.ly,137740,10189,200,1

In [27]:
swahili_data_dataset['Status Code'].value_counts()

Status Code
 200    8
-1      1
Name: count, dtype: int64

In [28]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
swahili_data_dataset.loc[swahili_data_dataset['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [29]:
swahili_data_dataset['Status Code'].value_counts()

Status Code
 200    8
-1      1
Name: count, dtype: int64

In [30]:
print(len(swahili_data_dataset[(swahili_data_dataset['Status Code']==200) & (swahili_data_dataset['ham']==1)]))
print(len(swahili_data_dataset[(swahili_data_dataset['Status Code']==200) & (swahili_data_dataset['spam']==1)]))

8
0

In [31]:
swahili_data_dataset['Parked'].value_counts()

Parked
0    5
1    4
Name: count, dtype: int64

In [32]:
print(len(swahili_data_dataset[(swahili_data_dataset['Parked']==1) & (swahili_data_dataset['ham']==1)]))
print(len(swahili_data_dataset[(swahili_data_dataset['Parked']==1) & (swahili_data_dataset['ham']==0)]))

4
0

In [33]:
swahili_data_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,1,0,www.zap.co.mz,www.zap.co.mz,7707,10,200,0
1,1,0,http://onelink.to/xanf67,onelink.to,301512,2288,200,0
2,1,0,https://onelink.to/xanf67,onelink.to,301512,2288,200,0
3,1,0,http://movtv.co.mz,movtv.co.mz,0,0,-1,0
4,1,0,https://bit.ly/M-PesaTC,bit.ly,137740,10189,200,1

In [34]:
swahili_data_dataset.to_csv('../URL Data/swahili_data Websites Analysis.csv', index=None)

In [35]:
len(swahili_data_dataset)

9